import { readFileSync } from "node:fs";
import { extractOfficialTextEvents } from "../scripts/eventPipeline.mjs";
const reg = JSON.parse(readFileSync("data/event-sources-los-angeles.json", "utf8"));
const src = reg.sources.find((s) => s.id === "fiesta-hermosa-2026");
console.log("gates:", src.officialTextEvents[0].requiredText);
const res = await fetch(src.url, { headers: { "user-agent": "saturday-with-friends/0.1 event-ingest" } });
const html = await res.text();
console.log("bytes:", html.length);
const events = extractOfficialTextEvents(html, src, { now: new Date("2026-08-30T12:00:00Z"), windowDays: 45 });
console.log("extracted:", events.length);
