// Render-time resolution of the weekly "Popular this weekend" picks
// (public/data/{metro}/popular-events.json, generated by
// scripts/generate-popular-events.mjs). The dataset is editorial + audience
// specific, windowed to one Sat/Sun in metro-local time, and expires — a
// stale/empty/mismatched file degrades to an empty list, never a wrong one.

import { isUpcomingEvent } from "./eventFreshness";

export type PopularPick = {
  eventId: string;
  rank: number;
  reason?: string;
  clicks7d?: number | null;
};

export type PopularEventsDataset = {
  schemaVersion?: number;
  metroId?: string;
  audience?: string;
  generatedAt?: string;
  weekendStart?: string;
  weekendEnd?: string;
  note?: string;
  picks?: PopularPick[];
};

type PopularCandidate = {
  id: string;
  startDateTime?: string | null;
  endDateTime?: string | null;
};

// Same local-date math the feed uses to bucket days (WeekendView dateKey), so
// an event shown on Saturday in the feed lands in the same window here.
export function dateKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// True when the event's start date falls on the given Sat/Sun weekend
// (metro-local dates, same bucket math as the weekend feed).
export function isWeekendWindowEvent(
  event: { startDateTime?: string | null },
  sat: Date,
  sun: Date,
): boolean {
  if (!event.startDateTime) return false;
  const startKey = dateKey(new Date(event.startDateTime));
  return startKey === dateKey(sat) || startKey === dateKey(sun);
}

export type ResolvePopularEventsOptions<T extends PopularCandidate = PopularCandidate> = {
  dataset: PopularEventsDataset | null | undefined;
  events: T[];
  sat: Date;
  sun: Date;
  timeZone?: string;
  now?: Date;
};

// Feed ids end in a 10-char content hash that includes the start time, so a
// date or venue edit rotates the id (scripts/eventPipeline.mjs). A pick can go
// stale while the file itself is still the right weekend; the slug stem — the
// id minus that hash — is the stable identity.
const idStem = (id: string): string => String(id ?? "").replace(/-[0-9a-f]{10}$/, "");

export function resolvePopularEvents<T extends PopularCandidate>({
  dataset,
  events,
  sat,
  sun,
  timeZone,
  now,
}: ResolvePopularEventsOptions<T>): T[] {
  if (!dataset || !Array.isArray(dataset.picks) || dataset.picks.length === 0) {
    return [];
  }
  // The file is a weekly snapshot; only apply it to the weekend it names.
  if (dataset.weekendStart !== dateKey(sat)) return [];

  const byId = new Map(events.map((event) => [event.id, event]));
  const byStem = new Map<string, T[]>();
  for (const event of events) {
    const stem = idStem(event.id);
    if (!stem) continue;
    const list = byStem.get(stem);
    if (list) list.push(event);
    else byStem.set(stem, [event]);
  }
  // Candidate order: the picked session, then its rotated-id twins earliest
  // first. The first candidate that is still upcoming and inside the window
  // wins — filtering after choosing would let a past sibling eat the pick.
  const candidatesFor = (eventId: string): T[] => {
    const exact = byId.get(eventId);
    const siblings = byStem.get(idStem(eventId)) || [];
    return [
      ...(exact ? [exact] : []),
      ...siblings
        .filter((event) => event !== exact)
        .sort((a, b) =>
          String(a.startDateTime ?? "").localeCompare(String(b.startDateTime ?? "")),
        ),
    ];
  };
  const seen = new Set<string>();
  const out: T[] = [];

  const ranked = [...dataset.picks].sort((a, b) => {
    const ra = Number.isFinite(a.rank) ? a.rank : Number.MAX_SAFE_INTEGER;
    const rb = Number.isFinite(b.rank) ? b.rank : Number.MAX_SAFE_INTEGER;
    return ra - rb;
  });

  for (const pick of ranked) {
    const event = candidatesFor(pick.eventId).find(
      (candidate) =>
        !seen.has(candidate.id) &&
        isUpcomingEvent(candidate, now, timeZone ? { timeZone } : undefined) &&
        isWeekendWindowEvent(candidate, sat, sun),
    );
    if (!event) continue; // id not in the live feed this week
    seen.add(event.id);
    out.push(event);
  }

  return out;
}
